# Generated by Django 3.1.5 on 2021-02-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210223_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/uploads/profile_pics/default.jpg', upload_to=''),
        ),
    ]
