# Generated by Django 3.1.5 on 2021-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210223_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default_img.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
