# Generated by Django 3.1.5 on 2021-02-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20210224_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='USER',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_orgainser',
            field=models.BooleanField(default=True),
        ),
    ]
