# Generated by Django 3.1.5 on 2021-02-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20210224_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_orgainser',
            new_name='is_organiser',
        ),
    ]
