# Generated by Django 3.1.5 on 2021-02-24 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20210224_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phoned',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='special_files',
        ),
        migrations.AddField(
            model_name='agent',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default_img.jpg', upload_to='uploads/profile_pictures'),
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(default='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='new@crm.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('', 'Select the Source'), ('Social Media', 'Social Media'), ('NewsLetter', 'Newsletter'), ('Ads', 'Advertisements'), ('Friend_Family', 'Friend or Family'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
