# Generated by Django 3.1.5 on 2021-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20210224_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='No Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default_img.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
