# Generated by Django 3.1.5 on 2021-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20210224_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
