# Generated by Django 3.1.5 on 2021-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20210225_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
